### ISSUE TITLE
explanation folder and pre-explanation folder

### ISSUE THREAD

**Issue by huifenghc** [guillaumejs2403/ACE#1]
Hello

After running the bash scripts in the 'script' folder,  i found that there are two subfolders (explanstion、pre-explanation) in folder 'Results'.   But I have a problem with "explanation folder" and "pre-explanation folder" ，I guess the content in the pre-explanation folder corresponds to the first step in Figure 1 of the paper,  and use  "postprocessing.py" to process pre-explanation folder corresponds to the second step. 

I would like to know what is under folder explanation.

Thank you for your help

**Comment by guillaumejs2403** [comment]
Hi!

No, the "pre-explanation" folder is the result from Figure 1a  (i.e. the adversarial attacks through the DDPM), not Figure 1 in general.  The explanation folder holds the post-processing step - section 3.2 or Figure 1b-. In the main.py script, we already post-process everything and store it in the "explanation" folder, but we decided to store also the pre-explanations to avoid creating the first step multiple times (if you want to explore the hyperparameters, for example).

**Comment by huifenghc** [comment]
Thank you for solving my confusion.

**Comment by guillaumejs2403** [comment]
No problem!
