### ISSUE TITLE
CelebaA HQ Classifier

### ISSUE THREAD

**Issue by SKYzLine0401** [guillaumejs2403/ACE#4]
Hi!

I followed your steps to download and load the classifier, but for different input images, the output results of the classifier are similar. Could you please guide me on how to use the classifier to determine a smile or to judge age?
<img width="271" alt="test_1" src="https://github.com/guillaumejs2403/ACE/assets/73148964/025ef566-a2f5-424c-9c75-3fbcd6a93dea">
<img width="269" alt="test_2" src="https://github.com/guillaumejs2403/ACE/assets/73148964/5e0a72b7-08d9-431c-903a-b3c03662492f">

**Comment by guillaumejs2403** [comment]
Hi,

When instantiating the classifier, to chose smile, use the `query_label = 1` parameter. For age, use `query_label = 2`.  Further, use a normalization of `mean=[0.5] * 3` and `std=[0.5] * 3`.  Please check [this link](https://github.com/guillaumejs2403/ACE/blob/main/models/__init__.py#L17) where we create the networks.

The output shows three probabilities (assuming you are using the parameter `before_sigmoid = False` in the forward). The first one is probability of male, the second one probability of smile and the last one probability of young.

**Comment by SKYzLine0401** [comment]
Thank you for your answer.I made a mistake myself, forgot to use .eval() to enable evaluation mode.

**Comment by guillaumejs2403** [comment]
Ok :), I will close the issue, but if you don't have any other question feel free to open it again
