### ISSUE TITLE
Hyperparameter of the models

### ISSUE THREAD

**Issue by Ethanoool** [guillaumejs2403/ACE#6]
Can I get the hyperparameters of the CelebA model? I can't load the model as I can't get the hyperparameters such as number of blocks right.

**Comment by guillaumejs2403** [comment]
Hi,

The parameters are in main/scripts/celeba-attack.sh

Just in case, the parameters are as follows:
MODEL_FLAGS="--image_size 128 --attention_resolutions 32,16,8 --class_cond False --diffusion_steps 500 --learn_sigma True --noise_schedule linear --num_channels 128 --num_heads 4 --num_res_blocks 2 --resblock_updown True --use_fp16 True --use_scale_shift_norm True"
